server:
  port: 10400

logging:
  level:
    org.springframework: debug
    com.neusoft.mapper: debug

spring:
  application:
    name: cart-server
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/elm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.neusoft.po